version: '3'
services:
  supercias-slave-service:
    image: supercias
    command: npm run slave
    volumes:
      - /home/telix/data-mining/supercias/storage/:/home/pptruser/supercias/storage/
    network_mode: host
    restart: always


# run docker compose
# sudo docker-compose up --scale supercias-slave-service=1
