version: '3'
services:
  supercias-slave-service:
    image: supercias_consulta_personal
    command: npm run slave
    volumes:
      - /home/terac/data-mining/supercias/storage/:/home/pptruser/supercias/storage
    network_mode: host
    restart: always


# run docker compose
# sudo docker-compose up --scale supercias-slave-service=1
